### ISSUE TITLE
Wrong IP address?

### ISSUE THREAD

**Issue by psykix** [BlackSpruce/Air-ShareAPIDemo#1]
Hi, I'm using Air-Share on my Shield TV but when I generate a unique URL, the IP address is incorrect?

I'm not using wifi on my Shield TV, I'm using Ethernet.

I've tried rebooting, closing the app and regenerating etc.

Any ideas?

**Comment by BlackSpruce** [comment]
There is a problem at boot time with the Android TV Ethernet interface and
I am working on a fix for the next release. To workaround the issue; go to
settings and disable the server mode then exit the app using the top left
nav drawer. Restart the app and enable server mode. That should give the
correct IP.
Blackspruce

**Comment by psykix** [comment]
Thanks for the reply. I've tried that to no avail.

I set Server Mode to Disable Incoming Shares. The exit.

I even tried force stopping the app, since it appeared to still be running after exiting.

At the top, Network Status always says Wifi Direct P2P - not sure if this is correct.

Cheers :-)

**Comment by BlackSpruce** [comment]
If it says WiFi p2p then there is some other problem. That is the first
reported instance of that issue. Sounds like the app is not finding the
Ethernet interface at all. Do you have the capability to run android debug
logcat for the device?

**Comment by psykix** [comment]
I'll be honest, this is pretty much the first Android device I've owned - I'm more used to Windows and iOS :-)

It's not rooted and that's the reason for trying out your app :-)

I did try connecting to wifi but it failed - not sure if you can have both Ethernet and wifi enabled at the same time tbh.

**Comment by psykix** [comment]
Sorted it. Disabled the server mode, unticked start on reboot , rebooted and then it picked up Ethernet :-)

Cheers!

**Comment by BlackSpruce** [comment]
Great.

**Comment by psykix** [comment]
I can now access it fine - however to follow up with a dumb question....

How do I get the apk from Google Play store to transfer across??

Cheers!

**Comment by BlackSpruce** [comment]
Choose help from apps menu and scroll down to the FAQ on side loading.

**Comment by psykix** [comment]
Yeah, I read that but being an Android novice I guess I'm being a little thick!

I'm basically trying to side load BBC iPlayer (as a starting point).

I guess in terms of the FAQ, I'm trying to do number 3) (sideload from my PC) from Google Play in my browser on my PC.

I suspect I could have got this all wrong in my head and may be trying the impossible!

**Comment by BlackSpruce** [comment]
This issue should be fixed in the latest release. 

Also I have updated the YouTube video for the app to give a good overview of how sideloading is done using two different techniques:
https://www.youtube.com/watch?v=UlHSCWUAiio

**Comment by psykix** [comment]
Just thought I would drop you an update! Everything working great in the latest version. Thanks for fixing :-)

**Comment by BlackSpruce** [comment]
great stuff.

On Thu, Jul 30, 2015 at 9:43 AM, psykix notifications@github.com wrote:

> Closed #1 https://github.com/BlackSpruce/Air-ShareAPIDemo/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BlackSpruce/Air-ShareAPIDemo/issues/1#event-369403944
> .

## 

BlackSpruce Software
Maker of "Let's Print Droid" Cloud free printing for Android.

See my new app Air-Share, extends the Share option in all your apps to
share content across your WiFi network.
https://play.google.com/store/apps/details?id=com.blackspruce.gloo
